return {
  -- url = "https://gitlab.com/schrieveslaach/sonarlint.nvim",
  -- ft = {"cpp"},
  -- config = function()
  --   local mason_path = os.getenv("MASON")
  --   local mason_bin_path = mason_path .. "\\bin"
  --   require("sonarlint").setup({
  --     server = {
  --       cmd = {
  --         mason_bin_path .. "\\sonarlint-language-server",
  --         "-stdio",
  --         "-analyzers",
  --         vim.fn.expand(mason_path .. "/share/sonarlint-analyzers/sonarcfamily.jar"),
  --       },
  --     },
  --     filetypes = {
  --       "cpp",
  --     },
  --   })
  -- end,
}
